---
title: "R Notebook"
---
# Data Cleaning
## Process raw data
```{r}
# Read the raw dataset
hospital <- read.csv("~/Desktop/ADS_Proj2/Project2/Output/Hospital General Information.csv")
hospital$Phone.Number <- as.character(hospital$Phone.Number)

# Turn "Not Available" into NA, "Above Average" into 3, "Average" into 2 and "Below Average" into 1.
levels(hospital$Efficient.use.of.medical.imaging.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Timeliness.of.care.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Effectiveness.of.care.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Patient.experience.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Readmission.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Safety.of.care.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Mortality.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Hospital.overall.rating) <- c(1, 2, 3, 4, 5, NA)

# Save processed data
# save(hospital, file="~/Desktop/ADS_Proj2/Processed Data/hospital.RData")
```


## Add longtitude and latitude to dataset
```{r geo_codes, message=F}
# Transfer address into longtitude and latitude
# First 2500 data

library(ggmap)
library(dplyr)
hospital.geo=
  hospital[1:2500, ]%>%
  select(Address, City, State)%>%
  mutate(ADDRESS_Ext=paste(Address, City, State, sep=","))%>%
  mutate_geocode(ADDRESS_Ext)

hospital.geo$Name <- hospital$Hospital.Name[1:2500]
# Omit NA

hospital.geo <- na.omit(hospital.geo)
# Save first 2500 data
save(hospital.geo, file="~/Desktop/ads_proj2/Project2/Output/hospital_geo.RData")
```

```{r geo_codes, message=F}
# Transfer address into longtitude and latitude
# Remaining data
hospital.geo.1=
  hospital[2501:nrow(hospital), ]%>%
  select(Hospital.Name, Address, City, State)%>%
  mutate(ADDRESS_Ext=paste(Hospital.Name, Address, City, State, sep=","))%>%
  mutate_geocode(ADDRESS_Ext)

# Omit NA
hospital.geo.1 <- na.omit(hospital.geo.1)
# Save remaining data
save(hospital.geo.1, file="~/Desktop/ads_proj2/Project2/Output/hospital_geo1.RData")
```

```{r}
# Combine all data(first 2500 and last)
hospital.geo <- hospital.geo[, c(7, 1:6)]
hospital.geo <- hospital.geo[, c(2:7, 1)]
hospital.geo.1$Name <- hospital.geo.1$Hospital.Name 
hospital.geo.1 <- hospital.geo.1[, c(8, 2:7)]
hospital.geot <- rbind(hospital.geo, hospital.geo.1)

# Save all data
save(hospital.geot, file="~/Desktop/ads_proj2/Project2/Output/hospital_geot.RData")
```

```{r}
# Merge all the necessary features and processed data into final dataset

# Merge hospital and hospital.geot into hos
hos <- merge(x = hospital, y = hospital.geot, by.x = c("Hospital.Name", "Address"), by.y = c("Name", "Address"), all.y = TRUE)
hos <- hos[, c(-20, -21)]   # delete reduplicated columns

# Change colnames of hos
colnames(hos) <- c("Name","Address","City","State","ZIP.Code",  
                   "County.Name","Phone.Number","Type",  
                   "Hospital.Ownership","Emergency Services",  
                   "Overall Rating","Mortality.national.comparison",  
                   "Safety.of.care.national.comparison",  
                   "Readmission.national.comparison",  
                   "Patient.experience.national.comparison",  
                   "Effectiveness.of.care.national.comparison" ,  
                   "Timeliness.of.care.national.comparison",  
                   "Efficient.use.of.medical.imaging.national.comparison",  
                   "payment","ADDRESS_Ext","lon","lat")                    

# Save the final dataset
save(hos, file="~/Desktop/ads_proj2/Project2/Output/hos.RData")
```